version: "3.8"

services:
  db:
    build: ./docker/mysql
    command: --default_authentication_plugin=mysql_native_password
    # command: mysqld --character-set-server=utf8 --collation-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    volumes:
      - db-store:/var/lib/mysql

  web:
    image: nginx:1.21.3-alpine
    ports:
      - 8000:8000
    volumes:
      - ./src:/workspace
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
    working_dir: /workspace
    depends_on:
      - app

  app:
    build: ./docker/python
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/tmp.log
    volumes:
      - ./src:/workspace
    expose:
      - "8001"
    depends_on:
      - db
volumes:
  db-store:
